# Generated by Django 4.0.2 on 2022-03-09 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, null=True)),
                ('content', models.CharField(max_length=500, null=True)),
                ('author', models.CharField(max_length=50, null=True)),
                ('tags', models.CharField(max_length=100, null=True)),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start')),
                ('end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='end')),
                ('regdate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updates', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date published')),
            ],
        ),
    ]
