# Generated by Django 4.0.2 on 2022-03-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
