# Generated by Django 4.0.2 on 2022-03-14 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=500, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='')),
                ('regdate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updates', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date published')),
            ],
        ),
    ]
